Fix TypeError when using tuple.
$ python --version
Python 2.7.12

Traceback (most recent call last):
  File "makeDbAndEdl.py", line 819, in <module>
    endObjectProperties""" % (camera_name, globals()) )
TypeError: format requires a mapping